Repository njzjz/nodejs-wheel, pull requests merged in 2024-05, with the labels that each got.

#29 enable linux-aarch64 builds
  .github/workflows/build_wheel.yml
Labels: size/XS

#30 docs: update README
  README.md
Labels: size/S

#32 fix: fix dependencies of nodejs-wheel
  cmd/LICENSE
  cmd/README.md
  cmd/hatch_build.py
  cmd/pyproject.toml
  cmd/setup.py
Labels: size/L

#36 lint: add pre-commit and ruff configurations
  .pre-commit-config.yaml
  README.md
  cmd/README.md
  nodejs_wheel/executable.py
  pyproject.toml
Labels: size/M

#37 feat: add type annotations
  .pre-commit-config.yaml
  cmd/hatch_build.py
  nodejs_wheel/__init__.py
  nodejs_wheel/__main__.py
  nodejs_wheel/executable.py
  nodejs_wheel/py.typed
  pyproject.toml
  tests/test_api.py
Labels: size/M

#39 feat: add an argument to return `CompletedProcess`
  README.md
  nodejs_wheel/executable.py
  tests/test_api.py
Labels: size/L

#41 fix some issues with the types
  nodejs_wheel/executable.py
Labels: size/M

#43 ci(build): enable musllinux
  .github/workflows/build_wheel.yml
  README.md
  pyproject.toml
Labels: size/XS
