Repository njzjz/nodejs-wheel, pull requests merged in 2024-04, with the labels that each got.

#24 feat: allow passing args to node/npm/npx()
  nodejs_wheel/executable.py
Labels: size/S

#25 feat: add a package without CLI
  .github/workflows/build_wheel.yml
  README.md
  cmd/README.md
  cmd/pyproject.toml
  cmd/setup.py
  pyproject.toml
Labels: size/M

#26 add Python API
  README.md
  cmd/pyproject.toml
  nodejs_wheel/__init__.py
  nodejs_wheel/executable.py
  pyproject.toml
  tests/test_api.py
Labels: size/L
